name: Run ImmoAgent Hourly

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:     # allows manual triggering

jobs:
  run-immoagent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r Project/requirements.txt
          
      - name: Install SSL certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates

      - name: Run ImmoAgent
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TELEGRAM_MAIN_BOT_TOKEN: ${{ secrets.TELEGRAM_MAIN_BOT_TOKEN }}
          TELEGRAM_MAIN_CHAT_ID: ${{ secrets.TELEGRAM_MAIN_CHAT_ID }}
          TELEGRAM_BOT_VIENNA_TOKEN: ${{ secrets.TELEGRAM_BOT_VIENNA_TOKEN }}
          TELEGRAM_BOT_VIENNA_CHAT_ID: ${{ secrets.TELEGRAM_BOT_VIENNA_CHAT_ID }}
        run: |
          python Project/run.py
