version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: home-ai-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - home-ai-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: home-ai-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - home-ai-network

  # Home.ai Application
  home-ai:
    build: .
    container_name: home-ai-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - MONGODB_URI=mongodb://admin:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_ENDPOINT=minio:9000
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/var/log/home-ai
    depends_on:
      - mongodb
      - minio
    networks:
      - home-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: home-ai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - home-ai
    networks:
      - home-ai-network

volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local

networks:
  home-ai-network:
    driver: bridge 